/*
 * Copyright (c) 2026 Silicon Laboratories Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Replacement for the file generated by the Silicon Labs configurator. The
 * core includes it unconditionally, but only sl_cpc_init() and
 * sl_cpc_permanent_allocation() use the table. On Zephyr, each "silabs,ncp"
 * device initializes its own bus, so the table is never defined and those
 * functions are dropped by the linker.
 */

#ifndef SL_CPC_BUS_INSTANCES_H
#define SL_CPC_BUS_INSTANCES_H

#include <stdint.h>

#include "sl_cpc_bus.h"

extern sl_cpc_bus_t *sl_cpc_bus_instances[];
extern const uint8_t sl_cpc_bus_instances_count;

#endif /* SL_CPC_BUS_INSTANCES_H */
