/*
 * Copyright (c) 2026 Silicon Laboratories Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Replacement for the component catalog generated by the Silicon Labs
 * configurator, restricted to what the CPC core looks at.
 */

#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

#include <zephyr/autoconf.h>

#define SL_COMPONENT_CATALOG_PRESENT

#ifdef CONFIG_CMSIS_RTOS_V2
#define SL_CATALOG_KERNEL_PRESENT
#endif

/* Map SLI_CPC_ASSERT() on __ASSERT(), see cpc_assert.h */
#define SL_CATALOG_CPC_NG_PORT_ASSERT_PRESENT

/* Route the CPC logs to the Zephyr logging subsystem, see sl_log_helper.h */
#ifdef CONFIG_LOG
#define SL_CATALOG_LOG_COMPONENT_PRESENT
#endif

#endif /* SL_COMPONENT_CATALOG_H */
