/*
 * Copyright (c) 2026 Silicon Laboratories Inc.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Replacement for the CPC configuration generated by the Silicon Labs
 * configurator (see config/sl_cpc_config.h in the component).
 */

#ifndef SL_CPC_CONFIG_H
#define SL_CPC_CONFIG_H

#include <zephyr/autoconf.h>

#include "sl_component_catalog.h"

/* CPC log level, from the silabs_cpc Zephyr log module */
#if CONFIG_SILABS_CPC_LOG_LEVEL >= 4
#define SL_CPC_LOG_LEVEL SL_LOG_CONFIG_LEVEL_DEBUG
#elif CONFIG_SILABS_CPC_LOG_LEVEL == 3
#define SL_CPC_LOG_LEVEL SL_LOG_CONFIG_LEVEL_INFO
#elif CONFIG_SILABS_CPC_LOG_LEVEL == 2
#define SL_CPC_LOG_LEVEL SL_LOG_CONFIG_LEVEL_WARN
#elif CONFIG_SILABS_CPC_LOG_LEVEL == 1
#define SL_CPC_LOG_LEVEL SL_LOG_CONFIG_LEVEL_ERROR
#else
#define SL_CPC_LOG_LEVEL SL_LOG_CONFIG_LEVEL_NONE
#endif

#define SL_CPC_DEBUG_SYSTEM_VIEW_LOG_CORE_EVENT 0
#define SL_CPC_DEBUG_SYSTEM_VIEW_LOG_EP_EVENT 0
#define SL_CPC_DEBUG_CORE_EVENT_COUNTERS 0
#define SL_CPC_DEBUG_EP_EVENT_COUNTERS 0

#endif /* SL_CPC_CONFIG_H */
